namespace JackRussell.Audio
{
    public enum SoundType
    {
        None,
        HomingAttackStart,
        Kick,
        SprintStart,
        Jump,
        RailStart,
        RailLoop,
        InhaleLoop,
        Spinz808,
        Bell,
        SprintSpeedUp,
        HomingIndicatorAppear,
        Dash,
        StarCollect,
        ParryIndicator,
        TurretLaserFire,
        EnemyAlerted,
        ParryAttackSuccess,
        Teleport,
        HeavyPunch,
        TentacleMoveStart,
        TentacleMoveEnd,
        DashPanelEnter,
        PressureCollectParticle,
        ZombieVaporize,
    }
}